// <auto-generated />
using System;
using CowRegister.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CowRegister.Migrations
{
    [DbContext(typeof(CattleContext))]
    [Migration("20231201171311_NullableEarletter")]
    partial class NullableEarletter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("CowRegister.Model.Cattle", b =>
                {
                    b.Property<long>("Enar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AbandonedStock")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivedStock")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birth")
                        .HasColumnType("TEXT");

                    b.Property<int>("Breed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EarLetter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MotherEnar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoteOfAbandon")
                        .HasColumnType("TEXT");

                    b.HasKey("Enar");

                    b.ToTable("Cattle");
                });
#pragma warning restore 612, 618
        }
    }
}
